version: '3'
services:
  web:
    container_name: 'workout-plan'
    image: 'workout-plan'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9080:80'
    depends_on:
      - 'postgres'
      - 'rabbitmq'

  postgres:
    ports:
      - '5432:5432'
    container_name: postgresql
    image: 'postgres:12'
    environment:
      POSTGRES_USER: workout
      POSTGRES_PASSWORD: workout
      POSTGRES_DB: workoutdb


  rabbitmq:
    ports:
      - '15672:15672'
      - '5672:5672'
    container_name: rabbitmq
    image: 'rabbitmq:3-management'